# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('matricula', models.CharField(max_length=7, unique=True)),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outros', 'Outros')], max_length=20)),
                ('periodo', models.IntegerField()),
                ('data_de_nascimento', models.DateField()),
                ('idioma', models.CharField(max_length=20)),
                ('nome_do_curso', models.CharField(max_length=40)),
                ('rua', models.CharField(max_length=60)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(max_length=15)),
                ('bairro', models.CharField(max_length=20)),
                ('cidade', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=9)),
                ('telefone_fixo', models.CharField(max_length=14)),
                ('celular', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=60, unique=True)),
            ],
        ),
    ]
