# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_respuc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('nome', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('coordenador_do_curso', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=20)),
                ('quantidade_de_alunos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('nome', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('endereco', models.CharField(max_length=60)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(max_length=15)),
                ('bairro', models.CharField(max_length=20)),
                ('cidade', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=2)),
                ('telefone', models.CharField(max_length=14)),
                ('CEP', models.CharField(max_length=9)),
                ('celular', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=60, unique=True)),
                ('vinculo', models.CharField(max_length=20)),
                ('site', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='voluntario',
            old_name='cep',
            new_name='CEP',
        ),
        migrations.RemoveField(
            model_name='voluntario',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='voluntario',
            name='id',
        ),
        migrations.AddField(
            model_name='voluntario',
            name='CPF',
            field=models.CharField(default=1, max_length=14, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
