# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_respuc', '0002_auto_20170202_0325'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParceiroExterno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPF', models.CharField(max_length=14)),
                ('CNPJ', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=60)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(max_length=15)),
                ('bairro', models.CharField(max_length=20)),
                ('cidade', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=2)),
                ('CEP', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='ParceiroInterno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ramal', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='CEP',
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='numero',
        ),
    ]
