# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_respuc', '0003_auto_20170203_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituicao',
            name='parceiro_externo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_respuc.ParceiroExterno'),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='parceiro_interno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_respuc.ParceiroInterno'),
        ),
    ]
