# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_respuc', '0004_auto_20170203_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instituicao',
            name='parceiro_externo',
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='parceiro_interno',
        ),
        migrations.AddField(
            model_name='parceiroexterno',
            name='instituicao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_respuc.Instituicao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parceirointerno',
            name='instituicao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_respuc.Instituicao'),
            preserve_default=False,
        ),
    ]
