# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_respuc', '0006_auto_20170203_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instituicao',
            old_name='email_instituicao',
            new_name='email',
        ),
        migrations.AddField(
            model_name='instituicao',
            name='email_responsavel',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instituicao',
            name='nome_responsavel',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instituicao',
            name='telefone_responsavel',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parceiroexterno',
            name='instituicao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_respuc.Instituicao'),
        ),
        migrations.AlterField(
            model_name='parceirointerno',
            name='instituicao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_respuc.Instituicao'),
        ),
    ]
