# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_respuc', '0007_auto_20170203_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='site',
        ),
        migrations.AddField(
            model_name='link',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_respuc.Instituicao'),
        ),
    ]
